//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepFit.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeepFit.Web.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокая.
        /// </summary>
        public static string ActivityType_Hight {
            get {
                return ResourceManager.GetString("ActivityType.Hight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Низкая.
        /// </summary>
        public static string ActivityType_Low {
            get {
                return ResourceManager.GetString("ActivityType.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя.
        /// </summary>
        public static string ActivityType_Middle {
            get {
                return ResourceManager.GetString("ActivityType.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная.
        /// </summary>
        public static string ActivityType_Minimum {
            get {
                return ResourceManager.GetString("ActivityType.Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень Высокая.
        /// </summary>
        public static string ActivityType_VeryHight {
            get {
                return ResourceManager.GetString("ActivityType.VeryHight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
    }
}
