// <auto-generated />
namespace KeepFit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Workouts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Workouts));
        
        string IMigrationMetadata.Id
        {
            get { return "201404161220423_Workouts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
