// <auto-generated />
namespace KeepFit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Excercises : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Excercises));
        
        string IMigrationMetadata.Id
        {
            get { return "201404160936246_Excercises"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
